"""
Django settings for imprenta_digital project.

Generated by 'django-admin startproject' using Django 5.2.1.
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- CARGAR VARIABLES DE ENTORNO (MANTENIBILIDAD) ---
load_dotenv(os.path.join(BASE_DIR, '.env'))

# --- CONFIGURACIÓN DE SEGURIDAD Y ENTORNO DINÁMICO ---
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-nhrr)tj=(n+3xu86-caa-0r*!nav5$q*5w!w_w_#r^mz@s0#5q')
DEBUG = os.getenv('DEBUG_MODE', 'False') == 'True'
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '*']

# NUEVO INTERRUPTOR PARA MODULARIDAD (MNT-SYS-04):
# Si el .env no dice nada, por defecto asume que el módulo SÍ está activo
MODULO_NOTAS_ACTIVO = os.getenv('ACTIVAR_NOTAS', 'True') == 'True'


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Backend.core',
    'Backend.facturas',
    'Backend.usuarios',
    'Backend.notas_de_debito_credito',
    'Backend.orden_de_entrega',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'imprenta_digital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'Frontend', 'Templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'imprenta_digital.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / os.getenv('DB_NAME', 'db.sqlite3'),
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'es'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATICFILES_DIRS = [
    BASE_DIR / "Frontend" / "Styles",
]
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = 'dashboard' 
LOGIN_URL = 'login' 
LOGOUT_REDIRECT_URL = 'login' 


# --- CONFIGURACIÓN DE AUDITORÍA Y LOGS (MANTENIBILIDAD MNT-SYS-01) ---
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'auditoria_sid.log',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}