name: QA Pipeline ISO 25010

on:
  push:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  auditoria:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Clonar el repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 2.5. Instalar dependencias del sistema (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y libcairo2-dev pkg-config

    - name: 3. Instalar dependencias de Python
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-json-report pylint radon
        pip install -r requirements.txt 
        playwright install chromium  # <--- ESTO ES NUEVO (Descarga el navegador)

    - name: 4. Ejecutar Pruebas Unitarias
      env:
        DJANGO_SETTINGS_MODULE: "imprenta_digital.settings"
        PYTHONPATH: "."
      run: pytest tests/unitarias --json-report --json-report-file=reporte_unitarias.json
      continue-on-error: true

    - name: 5. Ejecutar Pruebas de Integración
      env:
        DJANGO_SETTINGS_MODULE: "imprenta_digital.settings"
        PYTHONPATH: "."
      run: pytest tests/integracion --json-report --json-report-file=reporte_integracion.json
      continue-on-error: true

    - name: 6. Ejecutar Pruebas de Sistemas
      env:
        DJANGO_SETTINGS_MODULE: "imprenta_digital.settings_sistema"
        PYTHONPATH: "."
      run: |
        python manage.py migrate --settings=imprenta_digital.settings_sistema  # <--- ESTO ES NUEVO (Crea las tablas)
        pytest tests/sistemas --json-report --json-report-file=reporte_sistemas.json
      continue-on-error: true

    - name: 7. Consolidar Métricas (Tu Script)
      run: python tests/integracion/runner_iso25010.py
      
    - name: 8. Guardar Historial en GitHub
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add historico_grafana.json
        git commit -m "📊 QA: Actualización automática de métricas [skip ci]" || echo "No hay cambios para commitear"
        git push